outdir: '/DATA/scratch/usr/c.leemans/projects/DSB_protocol/results'
indir: '/DATA/projects/DSBrepair/data/SRA_data_DSBTRIP'

## META_INFO has to contain the following headers in a tab seperated file format:
# ID: unique identifier for experiment set (e.g. indelPCR and bcPCR pair)
# PCR_type: type of the PCR used [bcPCR, indelPCR or iPCR]
# file: name of the input file (path from indir directory)
META_INFO: '/DATA/scratch/usr/c.leemans/projects/DSB_protocol/config/metadata.txt'


structure:
  iPCR: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   10      -       const   present False   fixed   -
    constant_barcode       GTCACAAGGGCCGGCCACAA{16}TGATC  -       const_bar       present False   fixed   -
    rev_map_complement      -       TTAACCCTAGAAAGATAATCATATTGTGACGTAC      const   -       False   var   -
    rev_map GTACGTCACAATATGATTATCTTTCTAGGGTTAA      -       const   present True    fixed   4
    fwd_map_complement      -       GATCA[BC]TTGTGGCCGGCCCTTGTGAC     const_bar_comp  -       True    var   -

  indelPCR: |
    ID      5'      3'      type    req     second-read     pos   keep-bases
    index   10      -       const   present False   fixed   -
    constant_barcode       GTCACAAGGGCCGGCCACAA{16}TGATC   -       const_bar   present False   fixed   5


lev_dist: 2

min_count:
    iPCR: 3
    indelPCR: 0

## relevant for inDelphi init
celltype: K562

bowtie:
  index:  /DATA/data/human/hg38/index/bowtie2/hg38_1-22_XYM
  options:
      '1': ['--very-sensitive']
      '2': ['--very-sensitive-local']
max_dist:
  '1': 500
  '2': 20



crispr_info:
    LBR1:
        seq:
            "TGATCGGTACCAACTCCAGCAGGACCATGTGATCGAAAATGCCAAGTAGGA\
             AATTTGCCGATGGTGAAGTGGTAAGAGGTCGATGGCCTGGGAGTTCACTTT\
             ATTATGAAGTAGAAATTAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
        cut_site: 66
        pam_site: 69
        target:
            wt: 'CCGATGGTGAAGTGGTAA'
        spacer_list: ['TGGCCT', 'GGAGTT', 'CACTTT', 'ATTATG', 'GAAGTA', 'ATTAGA', 'GGAAGA']
        gap_list: [83, 90, 96, 102, 107, 116, 124]

    LBR2:
        seq:
            "TGATCGGTACCAACTCCAGCAGGACCATGTGATCGAAAATGCCAAGTAGGA\
             AATTTGCCGATGGTGAAGTGGTAAGAGGTCGATGGCCTGGGAGTTCACTTT\
             ATTATGAAGTAGAAATTAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
        cut_site: 73
        pam_site: 76
        target:
            wt: 'GTGGTAAGAGGTCGATGG'
            ssODN: 'GTGGTAAGAGATGTCGAT'
        spacer_list: ['TGGCCT', 'GGAGTT', 'CACTTT', 'ATTATG', 'GAAGTA', 'ATTAGA', 'GGAAGA']
        gap_list: [83, 90, 96, 102, 107, 116, 124]

    LBR12:
        seq:
            "TGATCGGTACCAACTCCAGCAGGACCATGTGATCGAAAATGCCAAGTAGGA\
             AATTTGCCGATGGTGAAGTGGTAAGAGGTCGATGGCCTGGGAGTTCACTTT\
             ATTATGAAGTAGAAATTAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
        cut_site: 80
        pam_site: 83
        target:
            wt: 'GTGAAGTGGTAAGAGGTCGA'
        spacer_list: ['TGGCCT', 'GGAGTT', 'CACTTT', 'ATTATG', 'GAAGTA', 'ATTAGA', 'GGAAGA']
        gap_list: [83, 90, 96, 102, 107, 116, 124]

    LBR15:
        seq:
            "TGATCGGTACCAACTCCAGCAGGACCATGTGATCGAAAATGCCAAGTAGGA\
             AATTTGCCGATGGTGAAGTGGTAAGAGGTCGATGGCCTGGGAGTTCACTTT\
             ATTATGAAGTAGAAATTAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
        cut_site: 92
        pam_site: 86
        target:
            wt: 'TGGCCTGGGAGTTCACTTTA'
        spacer_list: ['CACTTT','ATTATG', 'GAAGTA', 'ATTAGA', 'GGAAGA']
        gap_list: [96, 102, 107, 116, 124]

    default:
        seq:
            "TGATCGGTACCAACTCCAGCAGGACCATGTGATCGAAAATGCCAAGTAGGA\
             AATTTGCCGATGGTGAAGTGGTAAGAGGTCGATGGCCTGGGAGTTCACTTT\
             ATTATGAAGTAGAAATTAGATCGGAAGAGCACACGTCTGAACTCCAGTCAC"
        cut_site: 73
        pam_site: 76
        target:
            wt: 'GTGGTAAGAGGTCGATGG'
            ssODN: 'GTGGTAAGAGATGTCGAT'
        spacer_list: ['TGGCCT', 'GGAGTT', 'CACTTT', 'ATTATG', 'GAAGTA', 'ATTAGA', 'GGAAGA']
        gap_list: [83, 90, 96, 102, 107, 116, 124]
